views/ctos_consulta/views.py
from flask import Flask, render_template, redirect, url_for, request, abort,\
    session, Response, Blueprint
from flask_login import LoginManager, login_user, logout_user, login_required,\
    current_user
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func, column, table, select, asc, bindparam
import os
    # FORMULARIOS
from forms.forms import *
from forms.forms_fi import *
from forms.forms_am import *
from forms.forms_eyt import *
from forms.forms_iim import *
from forms.forms_lead import *
from forms.forms_hse import *
from forms.forms_org import *
from forms.forms_pm import *
from forms.forms_qm import *
from forms.forms_sn import *
from forms.forms_wpi import *
from forms.forms_ctos_edit import *

app = Flask(__name__)

ctos_consulta = Blueprint('ctos_consulta', __name__, template_folder='templates', static_folder='static')

# 1'S ====================================================================================================== #
@ctos_consulta.route('/menu/inicio/ctos/Slab1s/consulta/graph')
@login_required
def cto_consulta_slab_1s_graph(id='0'):
    from models.models import Cto1s_bosch_1, Ctofallas, Sku, Lineas, Areas
    # OPERACIONES
        # Fallas Cto
    #lista_fallas = [(c.falla) for c in Ctofallas.query.all()[0:]]
    #busqueda = Cto1s_bosch_1.query.order_by(Cto1s_bosch_1.fecha).all()
        # Ge
    lista_ge = ((c.ge)for c in Cto1s_bosch_1.query.all())
    suma_ge = [lista for lista in lista_ge]
    largo_ge = len(suma_ge)
    total_ge = sum(suma_ge)
    cambio_ge =  (total_ge / largo_ge ) / 100 * 100
    resul_ge = ("{:.2f}".format(cambio_ge))
    planned = 100 - cambio_ge
    no_planned = 100 - cambio_ge
        # Frecuencia fallas
    lista_frec = ((c.frec)for c in Cto1s_bosch_1.query.all())
    suma_frec = [lista for lista in lista_frec]
    total_frec = sum(suma_frec)
    # Consultas
    lineas = Lineas.query.all()[1:]
    fallas = Cto1s_bosch_1.query.all()[0:]
    areas = Areas.query.all()[1:]

    # Tabla
    paros = Cto1s_bosch_1.query.all()
    return render_template("Slab_1s/cto_slab_1s_consulta.html", fallas=fallas, lineas=lineas, areas=areas, resul_ge=resul_ge, 
    no_planned=no_planned, paros=paros, planned=planned, total_frec=total_frec)

@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_1s/')
@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_1s/<id>')
@login_required
def cto_consulta_slab_1s_registros(id='0'):
    from models.models import Cto1s_bosch_1, Ctofallas, Sku, Lineas, Areas, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    areas = Areas.query.get(id)
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
    areas = Areas.query.all()    
    return render_template("Resultados/slab_1s/vista_resultados.html", registro=registro, areas=areas)

@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_1s/<id>/view', methods=["get", "post"])
@login_required
def cto_consulta_slab_1s_registros_view(id):
    from models.models import Cto1s_bosch_1, Ctofallas, Sku, Lineas, Areas, Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    # Consulta al cto
    id = id
    slab_cto = Cto1s_bosch_1.query.get(id)
    # Formulario para editar
    cat = Cto1s_bosch_1.query.get(id)
    if cat is None:
        abort(404)
    form = FormCto1s_prototipo_edit(request.form, obj=cat)
    if form.validate_on_submit():
        form.populate_obj(cat)
        db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_consulta_capturas"))
    return render_template("Resultados/slab_1s/vista_resultados_id.html", form=form, slab_cto=slab_cto)

@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_1s/Bosch/<id>/view', methods=["get", "post"])
@login_required
def cto_consulta_slab_1s_bosch_2_registros_view(id):
    from models.models import Cto1s_bosch_2, Ctofallas, Sku, Lineas, Areas, Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    # Consulta al cto
    id = id
    slab_cto = Cto1s_bosch_2.query.get(id)
    # Formulario para editar
    cat = Cto1s_bosch_2.query.get(id)
    if cat is None:
        abort(404)
    form = FormCto1s_bosch_2_edit(request.form, obj=cat)
    if form.validate_on_submit():
        form.populate_obj(cat)
        db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_consulta_capturas"))
    return render_template("Resultados/slab_1s/vista_resultados_id.html", form=form, slab_cto=slab_cto)

@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_1s/<id>/delete', methods=["get", "post"])
@login_required
def cto_consulta_slab_1s_registros_delete(id):
    from models.models import Cto1s_bosch_1, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    cat = Cto1s_bosch_1.query.get(id)
    if cat is None:
        abort(404)
    form = FormSINO()
    if form.validate_on_submit():
        if form.si.data:
            db.session.delete(cat)
            db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_consulta_capturas"))
    return render_template("delete_elemento.html", form=form, cat=cat)

@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_1s/Bosch_2/<id>/delete', methods=["get", "post"])
@login_required
def cto_consulta_slab_1s_bosch_2_registros_delete(id):
    from models.models import Cto1s_bosch_2, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    cat = Cto1s_bosch_2.query.get(id)
    if cat is None:
        abort(404)
    form = FormSINO()
    if form.validate_on_submit():
        if form.si.data:
            db.session.delete(cat)
            db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_consulta_capturas"))
    return render_template("delete_elemento.html", form=form, cat=cat)
# 6'S ====================================================================================================== #
@ctos_consulta.route('/menu/inicio/ctos/Slab6s/consulta/graph')
@login_required
def cto_consulta_slab_6s_graph(id='1'):
    from models.models import Cto6s_prototipo_l1, Cto6s_prototipo_l2, Cto6s_prototipo_l3, Cto6s_prototipo_l4,\
        Ctofallas, Sku, Lineas, Areas
    # OPERACIONES
        # Ge consulta de resultados
    lista_ge = ((c.ge)for c in Cto6s_prototipo_l1.query.all())
    suma_ge = [lista for lista in lista_ge]
    lista_l2 = ((c.ge)for c in Cto6s_prototipo_l2.query.all())
    suma_l2 = [lista for lista in lista_l2]
    lista_l3 = ((c.ge)for c in Cto6s_prototipo_l3.query.all())
    suma_l3 = [lista for lista in lista_l3]
    lista_l4 = ((c.ge)for c in Cto6s_prototipo_l4.query.all())
    suma_l4 = [lista for lista in lista_l4]
        # Operacion con los resultados
    largo_ge = len(suma_ge + suma_l2 + suma_l3 + suma_l4)
    total_ge = sum(suma_ge + suma_l2 + suma_l3 + suma_l4)
    cambio_ge =  (total_ge / largo_ge ) / 100 * 100
    resul_ge = ("{:.2f}".format(cambio_ge))
    planned = 100 - cambio_ge
    no_planned = 100 - cambio_ge
        # Frecuencia fallas
    lista_frec = ((c.frec)for c in Cto6s_prototipo_l1.query.all())
    suma_frec = [lista for lista in lista_frec]
    lista_frec_l2 = ((c.frec)for c in Cto6s_prototipo_l2.query.all())
    suma_frec_l2 = [lista for lista in lista_frec_l2]
    lista_frec_l3 = ((c.frec)for c in Cto6s_prototipo_l3.query.all())
    suma_frec_l3 = [lista for lista in lista_frec_l3]
    lista_frec_l4 = ((c.frec)for c in Cto6s_prototipo_l4.query.all())
    suma_frec_l4 = [lista for lista in lista_frec_l4]
    total_frec = sum(suma_frec + suma_frec_l2 + suma_frec_l3 + suma_frec_l4)
    # Consultas
    lineas = Lineas.query.all()[1:]
    fallas = Cto6s_prototipo_l1.query.all()[0:]
    areas = Areas.query.all()[1:]
    # Tablas
    paros = Cto6s_prototipo_l1.query.all()
    linea_2 = Cto6s_prototipo_l2.query.all()
    linea_3 = Cto6s_prototipo_l3.query.all()
    linea_4 = Cto6s_prototipo_l4.query.all()
    return render_template("Slab_6s/cto_slab_6s_consulta.html", fallas=fallas, lineas=lineas, areas=areas, resul_ge=resul_ge, 
    no_planned=no_planned, paros=paros, planned=planned, total_frec=total_frec, linea_2=linea_2, linea_3=linea_3, linea_4=linea_4)

@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_6s/')
@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_6s/<id>')
@login_required
def cto_consulta_slab_6s_registros(id='0'):
    from models.models import Cto6s_prototipo_l1, Cto6s_prototipo_l2, Cto6s_prototipo_l3, Cto6s_prototipo_l4,\
        Ctofallas, Sku, Lineas, Areas, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto6s_prototipo_l1.query.all()
        registro_2 = Cto6s_prototipo_l2.query.all()
        registro_3 = Cto6s_prototipo_l3.query.all()
        registro_4 = Cto6s_prototipo_l4.query.all()
    else:
        registro = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_2 = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_3 = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_4 = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
    return render_template("Resultados/slab_6s/vista_resultados.html", registro=registro, registro_2=registro_2, 
    registro_3=registro_3, registro_4=registro_4)

# 6'S EDICION ====================================================================================================== #
@ctos_consulta.route('/menu/inicio/ctos/consulta/resultado/Slab_6s/<id>/view/l1', methods=["get", "post"])
@login_required
def cto_consulta_slab_6s_registros_view(id):
    from models.models import Cto6s_prototipo_l1, Ctofallas, Sku, Lineas, Areas, Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    # Consulta al cto
    id = id
    slab_cto = Cto6s_prototipo_l1.query.get(id)

views/ctos_consulta/templates/Resultados/slab_6s/vista_resultados.html
{% extends "layout.html" %}
{% block title %}Resultados CTO's{% endblock %}
{% block content %}
<div class="container-fluid mt--4">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Registro <span class="badge badge-info">Cto's</span></h3>
                </div>
                <div class="col-4 text-right">
                {% if current_user.is_authenticated() %}
                <a class="btn btn-primary btn-sm" href="{{url_for('ctos_consulta.cto_consulta_slab_6s_graph')}}" role="button">Todo 6's</a>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
          <!-- INICIO CARD -->
          <div class="row">

            <div class="col-md-12">
              <h3>Registro:</h3>
              <div class="card table-responsive">
                <table class="table" id="busqueda_filtro_completo">
                  <thead class="table-dark">
                    <tr>
                      <th>Fecha</th>
                      <th>Turno</th>
                      <th>Ge</th>
                      <th>Linea</th>
                      <th>Sección</th>
                      <th>Area</th>
                      {% if current_user.is_authenticated() %}
                      <th>View</th>
                      {% endif %}
                    </tr>
                  </thead>
                  {% for Registro in registro %}
                  <tr>
                    <td>{{Registro.fecha}}</td>
                    <td>{{Registro.turno}}</td>
                    <td>% {{Registro.ge}}</td>
                    <td>{{Registro.linea}}</td>
                    <td>{{Registro.seccion}}</td>
                    <td>{{Registro.area}}</td>
                    {% if current_user.is_authenticated %}
                    <td><a href="{{url_for('ctos_consulta.cto_consulta_slab_6s_registros_view',id=Registro.id)}}" class="btn btn-primary btn-sm">View</a></td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                  {% for Registro_2 in registro_2 %}
                  <tr>
                    <td>{{Registro_2.fecha}}</td>
                    <td>{{Registro_2.turno}}</td>
                    <td>% {{Registro_2.ge}}</td>
                    <td>{{Registro_2.linea}}</td>
                    <td>{{Registro_2.seccion}}</td>
                    <td>{{Registro_2.area}}</td>
                    {% if current_user.is_authenticated %}
                    <td><a href="{{url_for('ctos_consulta.cto_consulta_slab_6s_registros_view_l2',id=Registro_2.id)}}" class="btn btn-primary btn-sm">View</a></td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                  {% for Registro_3 in registro_3 %}
                  <tr>
                    <td>{{Registro_3.fecha}}</td>
                    <td>{{Registro_3.turno}}</td>
                    <td>% {{Registro_3.ge}}</td>
                    <td>{{Registro_3.linea}}</td>
                    <td>{{Registro_3.seccion}}</td>
                    <td>{{Registro_3.area}}</td>
                    {% if current_user.is_authenticated %}
                    <td><a href="{{url_for('ctos_consulta.cto_consulta_slab_6s_registros_view_l3',id=Registro_3.id)}}" class="btn btn-primary btn-sm">View</a></td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                  {% for Registro_4 in registro_4 %}
                  <tr>
                    <td>{{Registro_4.fecha}}</td>
                    <td>{{Registro_4.turno}}</td>
                    <td>% {{Registro_4.ge}}</td>
                    <td>{{Registro_4.linea}}</td>
                    <td>{{Registro_4.seccion}}</td>
                    <td>{{Registro_4.area}}</td>
                    {% if current_user.is_authenticated %}
                    <td><a href="{{url_for('ctos_consulta.cto_consulta_slab_6s_registros_view_l4',id=Registro_4.id)}}" class="btn btn-primary btn-sm">View</a></td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                </table>
              </div>
            </div>
            <!-- FIN CARD -->
          </div>
        </div>
      </div>
      <!-- Footer -->
      <footer class="footer pt-0">
          <div class="row align-items-center justify-content-lg-between">
              <div class="col-lg-6">
                  <div class="copyright text-center  text-lg-left  text-muted">
                      &copy; 2021 <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
                  </div>
              </div>
              <div class="col-lg-6">
                  <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                      <li class="nav-item">
                          <a href="" class="nav-link" target="_blank">Dashboard</a>
                      </li>
                  </ul>
              </div>
          </div>
      </footer>
    </div>
  </div>
</div>
{% endblock %}

views/ctos_consulta/templates/Resultados/slab_6s/vista_resultados_id.html
{% extends "mainpages/layout.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger">
{{ form[field].label }}: {{ ', '.join(errors) }}
</div>
{% endfor %}
<form method="post">
  {{ form.csrf_token }}
<div class="container-fluid mt--6">
  <div class="row justify-content-center">
    <div class=" col ">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">
                <span class="badge badge-warning">Edit - Captura: {{slab_cto.linea_cto}} {{slab_cto.linea}}</span>
              </h3>
            </div>
            <div class="col text-right">
              {% if current_user.is_admin() %}
              <a
                href="{{url_for('menus.menu_inicio_ctos_consulta_capturas')}}"
                class="btn btn-sm btn-primary">Regresar</a>
                {{form.enviar(class="btn btn-sm btn-warning")}}
              <!-- <a
                href="{{url_for('ctos_consulta.cto_consulta_slab_1s_graph')}}"
                class="btn btn-sm btn-success">Consultar Linea</a> -->
              {% endif %}
            </div>
          </div>
        </div>
      
        <div class="card-body">
          <div class="row">
              
            <!-- <div class="col-xl-7">
              <div class="card bg-translucent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="text-dark text-uppercase ls-1 mb-1">
                        GE Share
                      </h5>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    <div id="resultados_id_ge_pie_graph" style="width: 100%; height: 100%;"></div>
                    <table class="table" id="data_resultados_id_ge_pie" hidden>
                      <thead>
                        <tr>
                          <th>Share</th>
                          <th>Porcentaje</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>Ge</td>
                          <td>{{slab_cto.ge}}</td>
                        </tr>
                        <tr>
                          <td>No Planned</td>
                          <td>0.01</td>
                        </tr>
                        <tr>
                          <td>Planned</td>
                          <td>{{100 - (slab_cto.ge)}}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-xl-5">
              <div class="card bg-translucent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="text-dark text-uppercase ls-1 mb-1">
                        Failure Modes
                      </h5>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="chart">
                    <div id="resultados_id_fallas_bar" style="width: 100%; height: 100%;"></div>
                    <table class="table" id="data_resultados_id_fallas_bar" hidden>
                      <thead>
                        <tr>
                          <th>Modos</th>
                          <th>Minutos</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>{{slab_cto.falla}}</td>
                          <td>{{slab_cto.total}}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div> -->

            <div class="col-xl-4">
              <div class="card bg-translucent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="text-dark text-uppercase ls-1 mb-1">Datos Operador</h5>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <!-- INCIO Lineas -->
                    <table class="table align-items-center table-flush">
                      <tbody align="center">
                        <tr>
                          <th>Fecha:</th>
                          <td>{{form.fecha(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Turno:</th>
                          <td>{{form.turno(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr hidden>
                          <th>Sku:</th>
                          <td>{{form.sku(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Maquina:</th>
                          <td>{{form.maquina(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Lote Juliano</th>
                          <td>{{form.lote(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Linea:</th>
                          <td>{{form.linea(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>Codigo Sobre:</th>
                          <td>{{form.codigo_sobre(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Operador:</th>
                          <td>{{form.nombre_operador(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Lote Bobina:</th>
                          <td>{{form.lote_bobina(class="form-control form-control-sm")}}</td>
                        </tr>
                      </tbody>
                    </table>
                    <!-- FIN -->
                </div>
              </div>
            </div>

            <div class="col-xl-4">
              <div class="card bg-translucent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="text-dark text-uppercase ls-1 mb-1">Datos Operador</h5>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <!-- INCIO Lineas -->
                    <table class="table align-items-center table-flush">
                      <tbody align="center">
                        <tr>
                          <th>Tiempo Corrida:</th>
                          <td>{{form.tiempo_corrida(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Area</th>
                          <td>{{form.area(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Linea</th>
                          <td>{{form.linea_cto(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Año</th>
                          <td>{{form.year(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Planta</th>
                          <td>{{form.planta(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Seccion</th>
                          <td>{{form.seccion(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Bobina Consumida</th>
                          <td>{{form.bobina_consumida(class="form-control form-control-sm")}}</td>
                        </tr>
                        <tr>
                          <th>Total Display</th>
                          <td>{{form.total_display(class="form-control form-control-sm")}}</td>
                        </tr>
                      </tbody>
                    </table>
                    <!-- FIN -->
                </div>
              </div>
            </div>

            <div class="col-xl-4">
              <div class="card bg-translucent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="text-dark text-uppercase ls-1 mb-1">
                        Resultado
                      </h5>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <!-- INCIO Lineas -->
                    <table class="table align-items-center table-flush">
                      <tbody align="center">
                        <tr>
                          <th>T. Operativo:</th>
                          <td>{{form.tiempo_operativo(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>T. Usado</th>
                          <td>{{form.tiempo_usado(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>T. Maximo</th>
                          <td>{{form.tiempo_maximo(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>GE %</th>
                          <td>{{form.ge(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>Quality Loss</th>
                          <td>{{form.quality_loss(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>Speed Loss</th>
                          <td>{{form.speed_loss(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>Rework</th>
                          <td>{{form.rework(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                        <tr>
                          <th>Scrap</th>
                          <td>{{form.scrap(class="form-control form-control-sm", readonly=True)}}</td>
                        </tr>
                      </tbody>
                    </table>
                    <!-- FIN -->
                </div>
              </div>
            </div>

            <div class="col-xl-12">
              <div class="card bg-translucent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="text-dark text-uppercase ls-1 mb-1">
                        Fallas
                      </h5>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <!-- INCIO Lineas -->
                    <table class="table align-items-center table-flush">
                      <tbody align="center">
                        <tr>
                          <!-- <th>Loss:</th> -->
                          <th>Falla:</th>
                          <th>Frecuencia:</th>
                          <th>Total Min:</th>
                        </tr>
                        <tr>
                          <td>{{form.falla(class="form-control form-control-sm")}}</td>
                          <td>{{form.frec(class="form-control form-control-sm")}}</td>
                          <td>{{form.total(class="form-control form-control-sm")}}</td>
                        </tr>
                      </tbody>
                    </table>
                    <!-- FIN -->
                </div>
              </div>
            </div>

          </div>
        </div>
      </form>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul
          class="nav nav-footer justify-content-center justify-content-lg-end"
        >
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}