views/menus/views.py
from flask import Flask, render_template, redirect, url_for, request, abort,\
    session, Response, Blueprint
from flask_login import LoginManager, login_user, logout_user, login_required,\
    current_user
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
import os
    # FORMULARIOS
from forms.forms import *
from forms.forms_fi import *
from forms.forms_am import *
from forms.forms_eyt import *
from forms.forms_iim import *
from forms.forms_lead import *
from forms.forms_hse import *
from forms.forms_org import *
from forms.forms_pm import *
from forms.forms_qm import *
from forms.forms_sn import *
from forms.forms_wpi import *
from forms.forms_ctos_edit import *


app = Flask(__name__)

menus = Blueprint('menus', __name__, template_folder='templates', static_folder='static', static_url_path='/static/Pilares/')

@menus.route('/')
@menus.route('/menu/inicio')
@login_required
def menu_inicio():
    return render_template("inicio.html")

@menus.route('/menu/inicio/envio/ctos/')
@login_required
def menu_inicio_success_ctos():
    return render_template("success.html")

##  =========================================== MENU CTO'S ================================  ##
@menus.route('/menu/inicio/ctos')
@login_required
def menu_inicio_ctos():
    return render_template("Ctos/Entradas/ctos.html")
## ======================================= ENTRADAS
@menus.route('/menu/inicio/ctos/capturas')
@login_required
def menu_inicio_ctos_capturas():
    return render_template("Ctos/Entradas/ctos_capturas.html")

@menus.route('/menu/inicio/ctos/consulta_capturas')
@menus.route('/menu/inicio/ctos/consulta_capturas/<id>')
@login_required
def menu_inicio_ctos_consulta_capturas(id='0'):
    from models.models import Cto1s_bosch_1, Cto6s_prototipo_l1, Cto6s_prototipo_l2,\
        Cto6s_prototipo_l3, Cto6s_prototipo_l4, Cto1s_bosch_2, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
        registro_dos = Cto6s_prototipo_l1.query.all()
        registro_tres = Cto6s_prototipo_l2.query.all()
        registro_cuatro = Cto6s_prototipo_l3.query.all()
        registro_cinco = Cto6s_prototipo_l4.query.all()
        registro_seis = Cto1s_bosch_2.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
        registro_dos = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_tres = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_cuatro = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_cinco = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
        registro_seis = Cto1s_bosch_2.query.filter_by(RegistroId=id)
    return render_template("Ctos/Entradas/ctos_consulta_capturas.html", registro=registro, registro_dos=registro_dos, registro_tres=registro_tres,
                            registro_cuatro=registro_cuatro, registro_cinco=registro_cinco, registro_seis=registro_seis)

@menus.route('/menu/inicio/ctos/ctos_extracto_excel')
@menus.route('/menu/inicio/ctos/ctos_extracto_excel/<id>')
@login_required
def menu_inicio_ctos_extracto_excel(id='0'):
    from models.models import Cto1s_bosch_1, Cto6s_prototipo_l1, Cto6s_prototipo_l2,\
        Cto6s_prototipo_l3, Cto6s_prototipo_l4, Cto1s_bosch_2, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
        registro_dos = Cto6s_prototipo_l1.query.all()
        registro_tres = Cto6s_prototipo_l2.query.all()
        registro_cuatro = Cto6s_prototipo_l3.query.all()
        registro_cinco = Cto6s_prototipo_l4.query.all()
        registro_seis = Cto1s_bosch_2.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
        registro_dos = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_tres = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_cuatro = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_cinco = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
        registro_seis = Cto1s_bosch_2.query.filter_by(RegistroId=id)
    return render_template("Ctos/Entradas/ctos_extracto_excel.html", registro=registro, registro_dos=registro_dos,
                            registro_tres=registro_tres, registro_cuatro=registro_cuatro, registro_cinco=registro_cinco, registro_seis=registro_seis)
## ======================================= WATERFALL
@menus.route('/menu/inicio/ctos/ctos_extracto_gwf')
@menus.route('/menu/inicio/ctos/ctos_extracto_gwf/<id>')
@login_required
def menu_inicio_ctos_extracto_gwf(id='0'):
    from models.models import Cto1s_bosch_1, Cto6s_prototipo_l1, Cto6s_prototipo_l2,\
        Cto6s_prototipo_l3, Cto6s_prototipo_l4, Cto1s_bosch_2, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
        registro_dos = Cto6s_prototipo_l1.query.all()
        registro_tres = Cto6s_prototipo_l2.query.all()
        registro_cuatro = Cto6s_prototipo_l3.query.all()
        registro_cinco = Cto6s_prototipo_l4.query.all()
        registro_seis = Cto1s_bosch_2.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
        registro_dos = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_tres = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_cuatro = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_cinco = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
        registro_seis = Cto1s_bosch_2.query.filter_by(RegistroId=id)
    return render_template("Ctos/Waterfall/ctos_extracto_gwf.html", registro=registro, registro_dos=registro_dos, registro_tres=registro_tres,
                            registro_cuatro=registro_cuatro, registro_cinco=registro_cinco, registro_seis=registro_seis)
## ======================================= ADMINISTRACION
@menus.route('/menu/inicio/ctos/operadores')
@login_required
def menu_inicio_ctos_operadores():
    from models.models import Empleados_cto
    empleados = Empleados_cto.query.all()[1:]
    return render_template("Ctos/Administracion/ctos_operadores.html", empleados=empleados)

@menus.route('/menu/inicio/ctos/operadores/<id>/edit', methods=["get", "post"])
@login_required
def menu_inicio_ctos_operadores_edit(id):
    from models.models import Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    # Consulta al cto
    id = id
    slab_cto = Empleados_cto.query.get(id)
    # Formulario para editar
    cat = Empleados_cto.query.get(id)
    if cat is None:
        abort(404)
    form = FormEmpleados_cto(request.form, obj=cat)
    if form.validate_on_submit():
        form.populate_obj(cat)
        db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_operadores"))
    return render_template("Ctos/Administracion/ctos_operadores_edit.html", form=form, slab_cto=slab_cto)

@menus.route('/menu/inicio/ctos/operadores/<id>/delete', methods=["get", "post"])
@login_required
def menu_inicio_ctos_operadores_delete(id):
    from models.models import Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    cat = Empleados_cto.query.get(id)
    if cat is None:
        abort(404)
    form = FormSINO()
    if form.validate_on_submit():
        if form.si.data:
            db.session.delete(cat)
            db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_operadores"))
    return render_template("categorias_delete.html", form=form, cat=cat)

@menus.route('/menu/inicio/ctos/operadores/new', methods=["get", "post"])
@login_required
def menu_inicio_ctos_operadores_new():
    from models.models import Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    form = FormEmpleados_cto()
    # VALIDA EL FORM
    if form.validate_on_submit():
        art = Empleados_cto()
        # GRABA LA INFORMACION EN LA DATABASE
        form.populate_obj(art)
        db.session.add(art)
        db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_operadores"))
    else:
        return render_template("Ctos/Administracion/ctos_operadores_edit.html", form=form)

@menus.route('/menu/inicio/ctos/productos')
@login_required
def menu_inicio_ctos_productos():
    from models.models import Sku
    sku = Sku.query.all()
    return render_template("Ctos/Administracion/ctos_productos.html", sku=sku)

@menus.route('/menu/inicio/ctos/modos_de_fallo')
@login_required
def menu_inicio_ctos_modos_de_fallo():
    from models.models import Ctofallas, Cto_falla_slab_6s_l1 
    cto = Ctofallas.query.all()[1:]
    cto2 = Cto_falla_slab_6s_l1.query.all()[1:]
    return render_template("Ctos/Administracion/ctos_modos_de_fallos.html", cto=cto, cto2=cto2)

@menus.route('/menu/inicio/ctos/security')
@login_required
def menu_inicio_ctos_security():
    from models.models import Sku, Cto1s_bosch_1, Categorias, Lineas, Usuarios
    sku = Sku.query.all()
    cto = Cto1s_bosch_1.query.all()
    categoria = Categorias.query.all()
    lineas = Lineas.query.all()
    user = Usuarios.query.all()
    return render_template("Ctos/Administracion/ctos_security.html", sku=sku, cto=cto, categoria=categoria, lineas=lineas, user=user)

@menus.route('/menu/inicio/ctos/Jerarquia_de_Planta')
@login_required
def menu_inicio_ctos_jerarquia_de_planta():
    from models.models import Lineas, Areas, Secciones
    lineas = Lineas.query.all()[1:]
    areas = Areas.query.all()[1:]
    secciones = Secciones.query.all()[1:]
    return render_template("Ctos/Administracion/ctos_jerarquia.html", lineas=lineas, areas=areas, secciones=secciones)

##  =========================================== DASHBOARD ============================  ##
@menus.route('/menu/inicio/ctos/dashboard/reporte_del_turno')
@login_required
def menu_inicio_dashboard_reporte_del_turno(id='1'):

views/menus/templates/Ctos/Entradas/ctos.html
{% extends "mainpages/layout.html" %}
{% block title %}CTO's Menu{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-header bg-transparent">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="mb-0">
                        <span class="badge badge-warning">CTO's</span> -
                        Menu:
                    </h3>
                </div>
                <div class="col text-right">
                    <a href="{{url_for('menus.menu_inicio')}}" class="btn btn-sm btn-primary">Regresar</a>
                </div>
            </div>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-xl-6">
              <div class="card bg-transparent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col" align="center">
                      <h5 class="h2 text-dark mb-0">Entradas</h5>
                      <br>
                      <h6 class="text-muted text-uppercase ls-1 mb-1">Relación con CTO's</h6>
                    </div>
                  </div>
                </div>
                <div class="card-body mx-auto">
                  <!-- <a href="{{url_for('menus.menu_inicio_ctos')}}" class="btn btn-outline-primary btn-sm btn-block">Visitar</a> -->
                  <div class="dropdown">
                    <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Visitar
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_capturas')}}">Captura de CTO's</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_consulta_capturas')}}">Consulta Captura</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_extracto_excel')}}">Extracto Excel</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-6">
              <div class="card bg-transparent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col" align="center">
                      <h5 class="h2 text-dark mb-0">Dashboard</h5>
                      <br>
                      <h6 class="text-muted text-uppercase ls-1 mb-1">Cosulta de Registros</h6>
                    </div>
                  </div>
                </div>
                <div class="card-body mx-auto">
                  <!-- <a href="{{url_for('menus.menu_inicio_estandares')}}" class="btn btn-outline-primary btn-sm btn-block">Visitar</a> -->
                  <div class="dropdown">
                    <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Visitar
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_dashboard_reporte_del_turno')}}">Reporte del Turno</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_dashboard_ge')}}">GE</a>
                      <a class="dropdown-item" href="#" data-toggle="tooltip" data-placement="top" title="Próximamente">DMS Dashboard</a>
                      <a class="dropdown-item" href="#" data-toggle="tooltip" data-placement="top" title="Próximamente">Reporte Global de Planta</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-6">
              <div class="card bg-transparent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col" align="center">
                      <h5 class="h2 text-dark mb-0">Waterfall</h5>
                      <br>
                      <h6 class="text-muted text-uppercase ls-1 mb-1">Extracto a Waterfall</h6>
                    </div>
                  </div>
                </div>
                <div class="card-body mx-auto">
                  <!-- <a href="{{url_for('menus.menu_inicio_metas_2021')}}" class="btn btn-outline-primary btn-sm btn-block">Visitar</a> -->
                  <div class="dropdown">
                    <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Visitar
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_extracto_gwf')}}">Extracto a Waterfall</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-6">
              <div class="card bg-transparent">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">
                    <div class="col" align="center">
                      <h5 class="h2 text-dark mb-0">Administración</h5>
                      <br>
                      <h6 class="text-muted text-uppercase ls-1 mb-1">Administración del sitio</h6>
                    </div>
                  </div>
                </div>
                <div class="card-body mx-auto">
                  <!-- <a href="{{url_for('menus.menu_inicio_pilares_il6s')}}" class="btn btn-outline-primary btn-sm btn-block">Visitar</a> -->
                  <div class="dropdown">
                    <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Visitar
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_operadores')}}">Operadores</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_jerarquia_de_planta')}}">Jerarquia de Planta</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_productos')}}">Productos</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_modos_de_fallo')}}">Modos de Fallo</a>
                      <a class="dropdown-item" href="{{url_for('menus.menu_inicio_ctos_security')}}">Security</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul
          class="nav nav-footer justify-content-center justify-content-lg-end"
        >
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

views/menus/templates/Ctos/Entradas/ctos_capturas.html
{% extends "mainpages/layout.html" %}
{% block title %}CTO's Entradas{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="row align-items-center">
              <div class="col">
                  <h3 class="mb-0"><span class="badge badge-warning">Entradas</span> - Seleciona la Linea de CTO's:</h3>
              </div>
              <div class="col text-right">
                  <a href="{{url_for('menus.menu_inicio_ctos')}}" class="btn btn-sm btn-primary">Regresar</a>
              </div>
          </div>
        </div>

        <div class="container-fluid">
            <div class="header-body">
              <div class="row align-items-center py-4">
              </div>
              <div class="row">

                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">Trident Slab</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-warning"></i>
                        </div>
                      </div>
                      <br>
                      <div class="btn-group" role="group">
                        <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Linea
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                          <h6 class="dropdown-header text-center text-warning">Slab 1's</h6>
                          <a class="dropdown-item" href="{{url_for('ctos.cto_proto_2')}}">Bosch 1</a>
                          <a class="dropdown-item" href="{{url_for('ctos.cto_slab_1s_bosch_2')}}">Bosch 2</a>
                          <h6 class="dropdown-header text-center text-warning">Slab 6's</h6>
                          <a class="dropdown-item" href="{{url_for('ctos.cto_slab_6s_prototipo_l1')}}">Linea 1</a>
                          <a class="dropdown-item" href="{{url_for('ctos.cto_slab_6s_prototipo_l2')}}">Linea 2</a>
                          <a class="dropdown-item" href="{{url_for('ctos.cto_slab_6s_prototipo_l3')}}">Linea 3</a>
                          <a class="dropdown-item" href="{{url_for('ctos.cto_slab_6s_prototipo_l4')}}">Linea 4</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">Bubbalo</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">EVUP</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">Halls 1s</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>

                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">CFP Blister</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">CLG</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">SFP Blister</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">Halls Stick</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>

                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">Sugar Pellet Empaque</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">Trident 4s</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-xl-3 col-md-6">
                  <div class="card card-stats">
                    <!-- Card body -->
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <span class="h2 font-weight-bold mb-0">PBs Empaque</span>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-file-alt text-primary"></i>
                        </div>
                      </div>
                      <p class="mt-3 mb-0 text-sm">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Próximamente"><span class="badge badge-light">Próximamente</span></a>
                      </p>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>


      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul
          class="nav nav-footer justify-content-center justify-content-lg-end"
        >
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}