views/pizarrones_fi/views.py
from flask import Flask, render_template, redirect, url_for, request, abort,\
    session, make_response, Response, Blueprint
from flask_login import LoginManager, login_user, logout_user, login_required,\
    current_user
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
import os
    # FORMULARIO
from forms.forms import *
from forms.forms_fi import *

app = Flask(__name__)

pizarron_fi = Blueprint('pizarron_fi', __name__, template_folder='templates', static_folder='static', static_url_path='/static/upload')

@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu')
@login_required
def menu_pilares_fi():
    return render_template("pilares/FI/menu_pilares_fi.html")

@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero')
@login_required
def pizarron():
    from models.models import Notificaciones
    noti = Notificaciones.query.all()
        # Numero de noti
    lista = ((c.numero)for c in Notificaciones.query.all())
    suma = [lista for lista in lista]
    largo = len(suma)
    from models.models_mission_vision import Mission_fi, db
    from models.models_cbn import Cbn_fi, db
    from models.models_pilarlossmap import Pilarlossmap_fi, db
    from models.models_pilar_swot import Pilar_swot_fi, db
    id = '1'
    photo_1 = Mission_fi.query.filter_by(id=id)
    id = '2'
    photo_2 = Mission_fi.query.filter_by(id=id)
    id = '3'
    photo_3 = Mission_fi.query.filter_by(id=id)
    id = '4'
    photo_4 = Mission_fi.query.filter_by(id=id)
    dato = Cbn_fi.query.all()
    pilar = Pilarlossmap_fi.query.all()
    pilar_swot = Pilar_swot_fi.query.all()
    return render_template("tablero_fi_proto.html", dato=dato, pilar=pilar, photo_1=photo_1, photo_2=photo_2, photo_3=photo_3, 
                            photo_4=photo_4, pilar_swot=pilar_swot, noti=noti, largo=largo)

#@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero')
#@login_required
#def pizarron():
#    return render_template("tablero_fi.html")
###============================================ MISSION AND VISION ====================================================###
@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/mision', methods=["get", "post"])
@login_required
def tablero_fi_mision():
    from models.models_mission_vision import Mission_fi, db
    from models.models import Auditor_comentario, db
    id = '1'
    articulos = Mission_fi.query.filter_by(id=id)
        # COMENTARIO
    comentario = Auditor_comentario.query.all()[:1]
        # COMENTARIO EDIT
    id = '1'
    comment = Auditor_comentario.query.get(id)
    if comment is None:
        abort(404)
    form = FormAuditor_comentario(obj=comment)
    if form.validate_on_submit():
        # SI ENCUENTRA EL FORM SE SOBREESCRIBE
        form.populate_obj(comment)
        db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_mision"))
    return render_template("Mission_vision/mission.html", articulos=articulos, form=form, comentario=comentario)

@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/mision/<id>/edit', methods=["get", "post"])
@login_required
def tablero_fi_mision_fi_edit(id):
    from models.models_mission_vision import Mission_fi, db
    # Control de permisos
    if not current_user.is_user_fi() and current_user.is_admin():
        abort(404)
    art = Mission_fi.query.get(id)
    if art is None:
        abort(404)
    form = FormMission_fi(obj=art)
    if form.validate_on_submit():
        # Borramos la imagen anterior si hemos subido una nueva
        if form.photo.data:
            os.remove(app.root_path+'/static/upload/'+art.image)
            try:
                f = form.photo.data
                nombre_fichero = secure_filename(f.filename)
                f.save(app.root_path + '/static/upload/' + nombre_fichero)
            except:
                nombre_fichero = ''
        else:
            nombre_fichero = art.image
        form.populate_obj(art)
        art.image = nombre_fichero
        db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_mision"))
    return render_template("Mission_vision/mission_edit.html", form=form)

###============================================ ORGANIGRAMA ====================================================###
@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/organigrama', methods=["get", "post"])
@login_required
def tablero_fi_organigrama():
    from models.models_organigrama import Organigrama_fi
    from models.models import Auditor_comentario, db
    # COMENTARIO
    comentario = Auditor_comentario.query.all()[5:6]
    # COMENTARIO EDIT
    id = '6'
    comment = Auditor_comentario.query.get(id)
    if comment is None:
        abort(404)
    form = FormAuditor_comentario(obj=comment)
    if form.validate_on_submit():
        # SI ENCUENTRA EL FORM SE SOBREESCRIBE
        form.populate_obj(comment)
        db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_organigrama"))
        # MIEMBROS
    todo = Organigrama_fi.query.all()[1:]
    lider = Organigrama_fi.query.all()[0:1]
    return render_template("Organigrama/organigrama-pilar.html", form=form, comentario=comentario, todo=todo, lider=lider)

@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/organigrama/<id>/edit', methods=["get", "post"])
@login_required
def tablero_fi_organigrama_edit(id):
    from models.models_organigrama import Organigrama_fi, db
    # Control de permisos
    if not current_user.is_user_fi() and current_user.is_admin():
        abort(404)
    art = Organigrama_fi.query.get(id)
    if art is None:
        abort(404)
    form = FormOrganigrama_fi(obj=art)
    if form.validate_on_submit():
        # Borramos la imagen anterior si hemos subido una nueva
        if form.photo.data:
            os.remove(app.root_path+'/static/upload/organigrama/'+art.image)
            try:
                f = form.photo.data
                nombre_fichero = secure_filename(f.filename)
                f.save(app.root_path + '/static/upload/organigrama/' + nombre_fichero)
            except:
                nombre_fichero = ''
        else:
            nombre_fichero = art.image
        form.populate_obj(art)
        art.image = nombre_fichero
        db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_organigrama"))
    return render_template("Organigrama/organigrama-pilar_edit.html", form=form)

@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/organigrama/<id>/delete', methods=["get", "post"])
@login_required
def tablero_fi_organigrama_delete(id):
    from models.models_organigrama import Organigrama_fi, db
    # Control de permisos
    if not current_user.is_user_fi() and current_user.is_admin():
        abort(404)
    art = Organigrama_fi.query.get(id)
    if art is None:
        abort(404)
    form = FormSINO()
    if form.validate_on_submit():
        if form.si.data:
            if art.image != '':
                os.remove(app.root_path+'/static/upload/organigrama/'+art.image)
            db.session.delete(art)
            db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_organigrama"))
    return render_template("Pillar_loss/pilar-loss_delete.html", form=form, art=art)

@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/organigrama/new', methods=["get", "post"])
@login_required
def tablero_fi_organigrama_new():
    from models.models_organigrama import Organigrama_fi, db
    if not current_user.is_user_fi() and current_user.is_admin():
        abort(404)
    form = FormOrganigrama_fi()
    if form.validate_on_submit():
        try:
            f = form.photo.data
            nombre_fichero = secure_filename(f.filename)
            f.save(app.root_path + '/static/upload/organigrama/' + nombre_fichero)
        except:
            nombre_fichero = ''
        art = Organigrama_fi()
        form.populate_obj(art)
        art.image = nombre_fichero
        db.session.add(art)
        db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_organigrama"))
    else:
        return render_template("Organigrama/organigrama-pilar_edit.html", form=form)

###============================================ GRAFICA TEAM CAPABILITY ====================================================###
@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/grafica-capability', methods=["get", "post"])
@login_required
def tablero_fi_graficacapability():
    from models.models import Auditor_comentario, db
    # COMENTARIO
    comentario = Auditor_comentario.query.all()[11:12]
    # COMENTARIO EDIT
    id = '12'
    comment = Auditor_comentario.query.get(id)
    if comment is None:
        abort(404)
    form = FormAuditor_comentario(obj=comment)
    if form.validate_on_submit():
        # SI ENCUENTRA EL FORM SE SOBREESCRIBE
        form.populate_obj(comment)
        db.session.commit()
        return redirect(url_for("pizarron_fi.tablero_fi_graficacapability"))
    return render_template("Graph_team_capability/grafica-capability.html", form=form, comentario=comentario)

###============================================ PILLAR SWOT ====================================================###
@pizarron_fi.route('/menu/inicio/pilares_il6s/FI_menu/tablero/pilar-swot', methods=["get", "post"])
@login_required
def tablero_fi_pilarswot():
    from models.models_mission_vision import Mission_fi, db
    from models.models import Auditor_comentario, db
    from models.models_pilar_swot import Pilar_swot_fi, db
    dato = Pilar_swot_fi.query.all()
    id = '3'
    articulos = Mission_fi.query.filter_by(id=id)
    # COMENTARIO
    comentario = Auditor_comentario.query.all()[2:3]
    # COMENTARIO EDIT
    id = '3'
    comment = Auditor_comentario.query.get(id)
    if comment is None:
        abort(404)
    form = FormAuditor_comentario(obj=comment)
    if form.validate_on_submit():
        # SI ENCUENTRA EL FORM SE SOBREESCRIBE

views/pizarrones_fi/templates/Plan_90_dias/90-dias.html
{% extends "mainpages/layout.html" %}
{% block title %}Board - FI{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-transparent">
                    <div class="row">
                        <div class="col">
                        <h3 class="mb-0">
                            Plan 90 Dias
                        </h3>
                        </div>
                        <div class="col text-right">
                        <a href="{{url_for('pizarron_fi.pizarron')}}" class="btn btn-sm btn-primary">Regresar</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row icon-examples">
                        <!-- INICIO MISION VISION -->
                        <!-- FIN MISION VISION -->
                        <div class="col-xl-12">
                            <div class="card-footer text-primary" align="right">
                                <div class="card" style="width: 18rem;">
                                    <div class="card-body">
                                        <h5 class="card-title text-primary"><i class="far fa-comment-dots"></i> Comentario del Auditor</h5>
                                        <h5 class="card-text">{% for comen in comentario %}{{comen.comentario}}{% endfor %}</h5>
                                        {% if current_user.is_admin() or current_user.is_user_auditor() %}
                                            <a href="#" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#auditor" >Editar</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer class="footer pt-0">
        <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6">
                <div class="copyright text-center  text-lg-left  text-muted">
                    &copy; 2021 <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
                </div>
            </div>
            <div class="col-lg-6">
                <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                    <li class="nav-item">
                        <a href="" class="nav-link" target="_blank">Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<!-- Modal -->
<div class="modal fade" id="auditor">
    <form method="POST">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Comentario</h5>
                </div>
                <div class="modal-body">
                    {{ form.csrf_token }}
                    {{form.comentario(class="form-control form-control-sm text-primary")}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cerrar</button>
                    {{form.submit(class="btn btn-sm btn-warning", value="Guardar")}}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}