views/menus/views.py
from flask import Flask, render_template, redirect, url_for, request, abort,\
    session, Response, Blueprint
from flask_login import LoginManager, login_user, logout_user, login_required,\
    current_user
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
import os
    # FORMULARIOS
from forms.forms import *
from forms.forms_fi import *
from forms.forms_am import *
from forms.forms_eyt import *
from forms.forms_iim import *
from forms.forms_lead import *
from forms.forms_hse import *
from forms.forms_org import *
from forms.forms_pm import *
from forms.forms_qm import *
from forms.forms_sn import *
from forms.forms_wpi import *
from forms.forms_ctos_edit import *


app = Flask(__name__)

menus = Blueprint('menus', __name__, template_folder='templates', static_folder='static', static_url_path='/static/Pilares/')

@menus.route('/')
@menus.route('/menu/inicio')
@login_required
def menu_inicio():
    return render_template("inicio.html")

@menus.route('/menu/inicio/envio/ctos/')
@login_required
def menu_inicio_success_ctos():
    return render_template("success.html")

##  =========================================== MENU CTO'S ================================  ##
@menus.route('/menu/inicio/ctos')
@login_required
def menu_inicio_ctos():
    return render_template("Ctos/Entradas/ctos.html")
## ======================================= ENTRADAS
@menus.route('/menu/inicio/ctos/capturas')
@login_required
def menu_inicio_ctos_capturas():
    return render_template("Ctos/Entradas/ctos_capturas.html")

@menus.route('/menu/inicio/ctos/consulta_capturas')
@menus.route('/menu/inicio/ctos/consulta_capturas/<id>')
@login_required
def menu_inicio_ctos_consulta_capturas(id='0'):
    from models.models import Cto1s_bosch_1, Cto6s_prototipo_l1, Cto6s_prototipo_l2,\
        Cto6s_prototipo_l3, Cto6s_prototipo_l4, Cto1s_bosch_2, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
        registro_dos = Cto6s_prototipo_l1.query.all()
        registro_tres = Cto6s_prototipo_l2.query.all()
        registro_cuatro = Cto6s_prototipo_l3.query.all()
        registro_cinco = Cto6s_prototipo_l4.query.all()
        registro_seis = Cto1s_bosch_2.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
        registro_dos = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_tres = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_cuatro = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_cinco = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
        registro_seis = Cto1s_bosch_2.query.filter_by(RegistroId=id)
    return render_template("Ctos/Entradas/ctos_consulta_capturas.html", registro=registro, registro_dos=registro_dos, registro_tres=registro_tres,
                            registro_cuatro=registro_cuatro, registro_cinco=registro_cinco, registro_seis=registro_seis)

@menus.route('/menu/inicio/ctos/ctos_extracto_excel')
@menus.route('/menu/inicio/ctos/ctos_extracto_excel/<id>')
@login_required
def menu_inicio_ctos_extracto_excel(id='0'):
    from models.models import Cto1s_bosch_1, Cto6s_prototipo_l1, Cto6s_prototipo_l2,\
        Cto6s_prototipo_l3, Cto6s_prototipo_l4, Cto1s_bosch_2, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
        registro_dos = Cto6s_prototipo_l1.query.all()
        registro_tres = Cto6s_prototipo_l2.query.all()
        registro_cuatro = Cto6s_prototipo_l3.query.all()
        registro_cinco = Cto6s_prototipo_l4.query.all()
        registro_seis = Cto1s_bosch_2.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
        registro_dos = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_tres = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_cuatro = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_cinco = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
        registro_seis = Cto1s_bosch_2.query.filter_by(RegistroId=id)
    return render_template("Ctos/Entradas/ctos_extracto_excel.html", registro=registro, registro_dos=registro_dos,
                            registro_tres=registro_tres, registro_cuatro=registro_cuatro, registro_cinco=registro_cinco, registro_seis=registro_seis)
## ======================================= WATERFALL
@menus.route('/menu/inicio/ctos/ctos_extracto_gwf')
@menus.route('/menu/inicio/ctos/ctos_extracto_gwf/<id>')
@login_required
def menu_inicio_ctos_extracto_gwf(id='0'):
    from models.models import Cto1s_bosch_1, Cto6s_prototipo_l1, Cto6s_prototipo_l2,\
        Cto6s_prototipo_l3, Cto6s_prototipo_l4, Cto1s_bosch_2, db
    # SE LLAMA LA VARIABLE DE LA TABLA
    if id == '0':
        registro = Cto1s_bosch_1.query.all()
        registro_dos = Cto6s_prototipo_l1.query.all()
        registro_tres = Cto6s_prototipo_l2.query.all()
        registro_cuatro = Cto6s_prototipo_l3.query.all()
        registro_cinco = Cto6s_prototipo_l4.query.all()
        registro_seis = Cto1s_bosch_2.query.all()
    else:
        registro = Cto1s_bosch_1.query.filter_by(RegistroId=id)
        registro_dos = Cto6s_prototipo_l1.query.filter_by(RegistroId=id)
        registro_tres = Cto6s_prototipo_l2.query.filter_by(RegistroId=id)
        registro_cuatro = Cto6s_prototipo_l3.query.filter_by(RegistroId=id)
        registro_cinco = Cto6s_prototipo_l4.query.filter_by(RegistroId=id)
        registro_seis = Cto1s_bosch_2.query.filter_by(RegistroId=id)
    return render_template("Ctos/Waterfall/ctos_extracto_gwf.html", registro=registro, registro_dos=registro_dos, registro_tres=registro_tres,
                            registro_cuatro=registro_cuatro, registro_cinco=registro_cinco, registro_seis=registro_seis)
## ======================================= ADMINISTRACION
@menus.route('/menu/inicio/ctos/operadores')
@login_required
def menu_inicio_ctos_operadores():
    from models.models import Empleados_cto
    empleados = Empleados_cto.query.all()[1:]
    return render_template("Ctos/Administracion/ctos_operadores.html", empleados=empleados)

@menus.route('/menu/inicio/ctos/operadores/<id>/edit', methods=["get", "post"])
@login_required
def menu_inicio_ctos_operadores_edit(id):
    from models.models import Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    # Consulta al cto
    id = id
    slab_cto = Empleados_cto.query.get(id)
    # Formulario para editar
    cat = Empleados_cto.query.get(id)
    if cat is None:
        abort(404)
    form = FormEmpleados_cto(request.form, obj=cat)
    if form.validate_on_submit():
        form.populate_obj(cat)
        db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_operadores"))
    return render_template("Ctos/Administracion/ctos_operadores_edit.html", form=form, slab_cto=slab_cto)

@menus.route('/menu/inicio/ctos/operadores/<id>/delete', methods=["get", "post"])
@login_required
def menu_inicio_ctos_operadores_delete(id):
    from models.models import Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    cat = Empleados_cto.query.get(id)
    if cat is None:
        abort(404)
    form = FormSINO()
    if form.validate_on_submit():
        if form.si.data:
            db.session.delete(cat)
            db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_operadores"))
    return render_template("categorias_delete.html", form=form, cat=cat)

@menus.route('/menu/inicio/ctos/operadores/new', methods=["get", "post"])
@login_required
def menu_inicio_ctos_operadores_new():
    from models.models import Empleados_cto, db
    # Control de permisos
    if not current_user.is_admin():
        abort(404)
    form = FormEmpleados_cto()
    # VALIDA EL FORM
    if form.validate_on_submit():
        art = Empleados_cto()
        # GRABA LA INFORMACION EN LA DATABASE
        form.populate_obj(art)
        db.session.add(art)
        db.session.commit()
        return redirect(url_for("menus.menu_inicio_ctos_operadores"))
    else:
        return render_template("Ctos/Administracion/ctos_operadores_edit.html", form=form)

@menus.route('/menu/inicio/ctos/productos')
@login_required
def menu_inicio_ctos_productos():
    from models.models import Sku
    sku = Sku.query.all()
    return render_template("Ctos/Administracion/ctos_productos.html", sku=sku)

@menus.route('/menu/inicio/ctos/modos_de_fallo')
@login_required
def menu_inicio_ctos_modos_de_fallo():
    from models.models import Ctofallas, Cto_falla_slab_6s_l1 
    cto = Ctofallas.query.all()[1:]
    cto2 = Cto_falla_slab_6s_l1.query.all()[1:]
    return render_template("Ctos/Administracion/ctos_modos_de_fallos.html", cto=cto, cto2=cto2)

@menus.route('/menu/inicio/ctos/security')
@login_required
def menu_inicio_ctos_security():
    from models.models import Sku, Cto1s_bosch_1, Categorias, Lineas, Usuarios
    sku = Sku.query.all()
    cto = Cto1s_bosch_1.query.all()
    categoria = Categorias.query.all()
    lineas = Lineas.query.all()
    user = Usuarios.query.all()
    return render_template("Ctos/Administracion/ctos_security.html", sku=sku, cto=cto, categoria=categoria, lineas=lineas, user=user)

@menus.route('/menu/inicio/ctos/Jerarquia_de_Planta')
@login_required
def menu_inicio_ctos_jerarquia_de_planta():
    from models.models import Lineas, Areas, Secciones
    lineas = Lineas.query.all()[1:]
    areas = Areas.query.all()[1:]
    secciones = Secciones.query.all()[1:]
    return render_template("Ctos/Administracion/ctos_jerarquia.html", lineas=lineas, areas=areas, secciones=secciones)

##  =========================================== DASHBOARD ============================  ##
@menus.route('/menu/inicio/ctos/dashboard/reporte_del_turno')
@login_required
def menu_inicio_dashboard_reporte_del_turno(id='1'):

views/menus/templates/Ctos/Administracion/ctos_jerarquia.html
{% extends "consultas/layout.html" %}
{% block title %}CTO's Administración - Jerarquía{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--4">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">
                <span class="badge badge-warning">Administración</span> -
                Jerarquía de Planta
              </h3>
            </div>
            <div class="col text-right">
              <a href="{{url_for('menus.menu_inicio_ctos')}}" class="btn btn-sm btn-primary">Regresar</a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="row">

            <div class="col-xl-4">
              <div class="card table-responsive">
                <div class="card-header border-0">
                  <div class="row">
                    <div class="col">
                      <h3 class="mb-0 text-warning">Secciones</h3>
                    </div>
                    <div class="col text-right">
                      {% if current_user.is_admin() %}
                      <a href="#" class="btn btn-sm btn-secondary" data-toggle="tooltip"
                        data-placement="top" title="Próximamente">Nueva Sección</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="card">
                  <table class="table table-sm table-flush">
                    <thead class="table-dark">
                      <tr align="center">
                        <th>Sección</th>
                        {% if current_user.is_authenticated and current_user.is_admin() %}
                        <th>Editar</th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for Secciones in secciones %}
                      <tr align="center">
                        <th>{{Secciones.seccion}}</th>
                        {% if current_user.is_authenticated and current_user.is_admin() %}
                        <td>
                          <a href="#" type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" data-placement="top"title="Próximamente">
                            <i class="fas fa-pencil-alt"></i>
                          </a>
                        </td>
                        {% endif %}
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            
            <div class="col-xl-4">
              <div class="card table-responsive">
                <div class="card-header border-0">
                  <div class="row">
                    <div class="col">
                      <h3 class="mb-0 text-warning">Áreas</h3>
                    </div>
                    <div class="col text-right">
                      {% if current_user.is_admin() %}
                      <a href="#" class="btn btn-sm btn-secondary" data-toggle="tooltip"
                        data-placement="top" title="Próximamente">Nueva Area</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="card">
                  <table class="table table-sm table-flush">
                    <thead class="table-dark">
                      <tr align="center">
                        <th>Area</th>
                        {% if current_user.is_authenticated and current_user.is_admin() %}
                        <th>Editar</th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for Areas in areas %}
                      <tr align="center">
                        <th>{{Areas.area}}</th>
                        {% if current_user.is_authenticated and current_user.is_admin() %}
                        <td>
                          <a href="#" type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" 
                          data-placement="top" title="Próximamente"><i class="fas fa-pencil-alt"></i></a>
                        </td>
                        {% endif %}
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            <div class="col-xl-4">
              <div class="card table-responsive">
                <div class="card-header border-0">
                  <div class="row">
                    <div class="col">
                      <h3 class="mb-0 text-warning">Lineas</h3>
                    </div>
                    <div class="col text-right">
                      {% if current_user.is_admin() %}
                      <a
                        href="#"
                        class="btn btn-sm btn-secondary"
                        data-toggle="tooltip"
                        data-placement="top"
                        title="Próximamente"
                        >Nueva Linea</a
                      >
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="card">
                  <table class="table table-sm table-flush">
                    <thead class="table-dark">
                      <tr align="center">
                        <th>Linea</th>
                        {% if current_user.is_authenticated and current_user.is_admin() %}
                        <th>Editar</th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for Lineas in lineas %}
                      <tr align="center">
                        <th>{{Lineas.linea}}</th>
                        {% if current_user.is_authenticated and current_user.is_admin() %}
                        <td>
                          <a href="#" type="button" class="btn btn-secondary btn-sm" data-toggle="tooltip" 
                          data-placement="top" title="Próximamente" ><i class="fas fa-pencil-alt"></i></a>
                        </td>
                        {% endif %}
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul
          class="nav nav-footer justify-content-center justify-content-lg-end"
        >
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

views/menus/templates/Ctos/Administracion/ctos_modos_de_fallos.html
{% extends "consultas/layout.html" %}
{% block title %}CTO's Administración - Fallos{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--4">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="row">
            <div class="col">
              <h3 class="mb-0"><span class="badge badge-warning">Administración</span> - Modo de Fallo</h3>
            </div>
            <div class="col text-right">
              <a href="{{url_for('menus.menu_inicio_ctos')}}" class="btn btn-sm btn-primary">Regresar</a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="col-xl-12">
            <form>
              <div class="card bg-transparent">
                <div class="card-header bg-transparent">
                  <div class="row">
                    <div class="col">
                      <h5 class="h3 text-dark text-white mb-0"><span class="badge badge-success">Filtro</span></h5>
                    </div>
                    <div class="col text-right">
                      <input type="reset" value="Limpiar Filtro" class="btn btn-sm btn-warning">
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <table style="width: 67%; margin: 0 auto 2em auto;">
                    <thead align="center">
                      <tr>
                        <th>Selección</th>
                        <th>Busqueda</th>
                      </tr>
                    </thead>
                    <tbody align="center">
                      <tr>
                        <td>Línea</td>
                        <td><input type="text" class="form-control form-control-sm custom-select global_filter" id="global_filter" list="lista_linea"></td>
                          <datalist id="lista_linea">
                            <option value="Slab 1's">
                            <option value="Slab 6s L1">
                          </datalist>
                      </tr>
                    </tbody>
                  </table>
                  <div class="col text-right">
                    <a class="btn btn-sm btn-warning" data-toggle="collapse" href="#Busqueda_modo_de_fallo">Buscar</a>
                  </div>
                </div>
              </div>
            </form>
          </div>

          <div class="col-md-12">
            <div class="card table-responsive">
              <div class="collapse fade" id="Busqueda_modo_de_fallo">
                <table class="table table-sm" id="filtro_menus_entradas_consulta_modo_de_falla" style="width: 100%; height: 100%;">
                  <thead class="table-dark">
                    <tr align="center">
                      <th>Numero</th>
                      <th>Falla</th>
                      <th>Perdida GWF</th>
                      <th hidden>Planta</th>
                      <th>Linea</th>
                      {% if current_user.is_authenticated and current_user.is_admin() %}
                      <th>Editar</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for Cto in cto %}
                    <tr align="center">
                      <td>{{Cto.numero}}</td>
                      <th>{{Cto.falla}}</th>
                      <th>{{Cto.perdida}}</th>
                      <th hidden>Puebla</th>
                      <th>{{Cto.linea}}</th>
                      {% if current_user.is_authenticated and current_user.is_admin() %}
                      <td>
                        <a href="{{url_for('cto_vistas_edit',id=Cto.id)}}" type="button" class="btn btn-warning btn-sm">
                          <i class="fas fa-pencil-alt"></i>
                        </a>
                      </td>
                      {% endif %}
                    </tr>
                    {% endfor %}
                    {% for Cto in cto2 %}
                    <tr align="center">
                      <td>{{Cto.numero}}</td>
                      <th>{{Cto.falla}}</th>
                      <th>{{Cto.perdida}}</th>
                      <th hidden>Puebla</th>
                      <th>{{Cto.linea}}</th>
                      {% if current_user.is_authenticated and current_user.is_admin() %}
                      <td>
                        <a href="{{url_for('cto_vistas_edit',id=Cto.id)}}" type="button" class="btn btn-warning btn-sm">
                          <i class="fas fa-pencil-alt"></i>
                        </a>
                      </td>
                      {% endif %}
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

views/menus/templates/Ctos/Administracion/ctos_operadores.html
{% extends "consultas/layout.html" %}
{% block title %}CTO's Administración - Operadores{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--4">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0"><span class="badge badge-warning">Administración</span> - Operadores</h3>
            </div>
            <div class="col text-right">
              <a href="{{url_for('menus.menu_inicio_ctos')}}" class="btn btn-sm btn-primary">Regresar</a>
              {% if current_user.is_authenticated and current_user.is_admin() %}
              <a href="{{url_for('menus.menu_inicio_ctos_operadores_new')}}" class="btn btn-sm btn-warning">Agregar
                Nuevo</a>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="row">

            <div class="col-xl-12">
              <form>
                <div class="card bg-transparent">
                  <div class="card-header bg-transparent">
                    <div class="row">
                      <div class="col">
                        <h5 class="h3 text-dark text-white mb-0"><span class="badge badge-success">Filtro</span></h5>
                      </div>
                      <div class="col text-right">
                        <input type="reset" value="Limpiar Filtro" class="btn btn-sm btn-warning">
                      </div>
                    </div>
                  </div>
                  <div class="card-body">
                    <table style="width: 67%; margin: 0 auto 2em auto;">
                      <thead align="center">
                        <tr>
                          <th>Selección</th>
                          <th>Busqueda</th>
                        </tr>
                      </thead>
                      <tbody align="center">
                        <tr>
                          <td>Número o Nombre </td>
                          <td><input type="text" class="form-control form-control-sm" id="myInputTextField"></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </form>
            </div>

            <div class="col-xl-12">
              <h3 class="mb-0"><span class="badge badge-warning">Registro</span></h3>
              <div class="card table-responsive">
                <table class="table table-sm" id="filtro_menus_entradas_consulta_operadores">
                  <thead class="table-dark">
                    <tr align="center">
                      <th>N° de Operador</th>
                      <th>Nombre de Empleado</th>
                      {% if current_user.is_authenticated and current_user.is_admin() %}
                      <th>Editar</th>
                      <th>Borrar</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for Empleado in empleados %}
                    <tr align="center">
                      <td>{{Empleado.NumeroEmpleadoMondelez}}</td>
                      <td>{{Empleado.NombreEmpleadoMondelez}}</td>
                      {% if current_user.is_authenticated and current_user.is_admin() %}
                      <td><a href="{{url_for('menus.menu_inicio_ctos_operadores_edit',id=Empleado.id)}}"
                          class="btn btn-warning btn-sm"><i class="fas fa-pencil-alt"></i></a></td>
                      <td><a href="{{url_for('menus.menu_inicio_ctos_operadores_delete',id=Empleado.id)}}"
                          class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a></td>
                      {% endif %}
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}

views/menus/templates/Ctos/Administracion/ctos_security.html
{% extends "consultas/layout.html" %}
{% block title %}CTO's Administración - Security{% endblock %}
{% block content %}
<!-- Page content -->
<div class="container-fluid mt--4">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header bg-transparent">
          <div class="row">
            <div class="col">
                <h3 class="mb-0"><span class="badge badge-warning">Administración</span> - Usuarios</h3>
            </div>
            <div class="col text-right">
                <a href="{{url_for('menus.menu_inicio_ctos')}}" class="btn btn-sm btn-primary">Regresar</a>
            </div>
        </div>
      </div>

        <div class="card-body table-responsive">
          <h3>Registro:</h3>
          <table class="table table-sm" id="search_box">
            <thead class="table-dark">
              <tr align="center">
                <th>Username</th>
                <th>Nombre</th>
                <th>Correo</th>
                {% if current_user.is_authenticated and current_user.is_admin() %}
                <th>Editar</th>
                <th>Borrar</th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
              {% for User in user %}
              <tr align="center">
                <td>{{User.username}}</td>
                <td>{{User.nombre}}</td>
                <td>{{User.email}}</td>
                {% if current_user.is_authenticated and current_user.is_admin() %}
                <td>
                  <a href="{{url_for('usuario.usuarios_edit',id=User.id)}}" type="button" class="btn btn-warning btn-sm">
                    <i class="fas fa-pencil-alt"></i>
                  </a>
                </td>
                <td>
                  <a href="{{url_for('usuario.usuarios_delete',id=User.id)}}" type="button" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash"></i>
                  </a>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
          &copy; 2021
          <a href="" class="font-weight-bold ml-1" target="_blank">Mondelez</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul
          class="nav nav-footer justify-content-center justify-content-lg-end"
        >
          <li class="nav-item">
            <a href="" class="nav-link" target="_blank">Dashboard</a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</div>
{% endblock %}